[workspace]
resolver = "3"
members = ["crates/*"]
default-members = ["crates/mediavert"]

[workspace.dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive", "unicode", "wrap_help"] }
ignore = "0.4.25"
termcolor = "1.4.1"
